### ISSUE TITLE
"Automatic animations have random offsets" on multiple rigged characters

### ISSUE THREAD

**Issue by te4monster** [victorfeitosa/hexen2-mdl-export-import#6]
Windows 10 64, Blender 2.93. Two different rigged characters, I've tried to export to MDL and each time I get this error. 
![quakebug](https://user-images.githubusercontent.com/16991638/125748288-4953dc14-0579-47ad-b4bb-eded5248f1d6.jpg)

**Comment by victorfeitosa** [comment]
Do you mind adding more details such as the properties in the MDL tab and how exactly are you trying to export everything? I'll try to reproduce it later.

**Comment by te4monster** [comment]
![quakeexporter_mdlpage](https://user-images.githubusercontent.com/16991638/126021587-558d511d-824a-44da-9645-b1262fc971b7.jpg)
![quakeexporter_pyconsole](https://user-images.githubusercontent.com/16991638/126021592-76a64ad8-564d-4a2e-b25b-01efc5d91de3.jpg)

I am selecting the mesh, not the mesh and skeleton. Then I go to Export and chose MDL.
This model works under a different exporter in Blender 2.81. I use the same method to export there as I do in 2.93.
Model: https://www.dropbox.com/s/p8xp0wxl8ss149m/QuakeoriginalMDL_03_293BLENDER.blend?dl=0

**Comment by victorfeitosa** [comment]
Alright, this is something that's coming from the newest version of Blender, it probably works under 2.81 as well but I have to double-check. Meanwhile I'll be working with a solution for the newest version. I just wish they stop messing around with the scripting API so much :/.

**Comment by victorfeitosa** [comment]
Hey @te4monster check out the latest version. I tested on my end and it worked. A few things to note though are
1- Make sure you apply your decimate modifiers, I added a warning in case there's any weird issue exporting triangles.
2- For armature-based animations, there's a known bug where before exporting the models are scaled and that causes armatures to ruin animations. So you'll have to scale the armature instead of setting a scale factor on export, and use a scale factor of 1.0
3- Make sure your textures look proper. Use nodes with textures in the first channel and you should be good.

Other than that, which I know might be too much, you should be good. I already added an issue to deal with the armature bug but as long as you don't mind scaling the armature yourself for now everything should look good.

Let me know if you run into any other issues and thanks for reporting this one 👍

**Comment by te4monster** [comment]
Will do, thanks.

**Comment by victorfeitosa** [comment]
I'll be closing this one until it pops again or another related issue comes up
